services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/app
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
